server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

message: "Order Service Configuration"

# Product Service URL for inter-service communication
product-service:
  url: http://localhost:8081