spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db_dev
    username: postgres
    password: dev_password

message: "Product Service - Development Environment"

logging:
  level:
    root: DEBUG